project_id = "tnjcigqqmwahnxcsljgk"

[functions.complete-course]
verify_jwt = false

[functions.translate-course]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.receive-signal]
verify_jwt = false

[functions.setup-trading-signals]
verify_jwt = false

